Error handling, generic types, structural change
miking-lang/miking-ipm pull request #7
Opened 2020-07-10 13:27 UTC by darthvader211

Previous state eventhandler added. Improved interaction

Co-authored-by: Moa <moaan@kth.se>
Co-authored-by: andnil5 <andnil5@kth.se>

2020-07-13 15:07 UTC, theoahfeldt requested changes
General suggestion: 
You use the name 'alfabeth' in your code, however the correct spelling is 'alphabet'. You might want to do a search and replace.

Particular comments:

2020-07-13 15:07 UTC, theoahfeldt commented on src/model/dfa.mc
> +	     l2s: a ->_ ->_ -> String
Type declarations are not totally correct. The 'alfabeth' and the labels do not consist of same type as the states right, if so shouldn't startState, acceptStates and s2s use another type variable (such as b)? Also why are s2s and l2s declared to take three arguments?

2020-07-13 15:07 UTC, theoahfeldt commented on src/model/dfa.mc
>  -- All labels for the transitions are chars. All labels between two states also has to be unique.
These comments should be updated since states and labels can now be of any type.

2020-07-13 15:07 UTC, theoahfeldt commented on src/model/gen.mc
>  end
Is it not more correct to call this function 'formatStates', as your comment suggest? There are a few more functions starting with 'parse' which should probably be changed to 'format'.

2020-07-13 15:08 UTC, aathn commented on README.md
> +>>>>>>> cd57ddb... dfa structure changed, added ID's, updated readme
You probably want to fix this

2020-07-13 15:08 UTC, aathn commented on src/visual/boot.js
> +		    fs.writeFile(__dirname +'/webpage/js/data-source.js', "let inputModel = '" + buf.toString().replace(/(\r\n|\n|\r)/gm, "") + "';" , function (err) {if (err) return console.log(err);});});return;
Try to avoid long rows like this: 80 characters is generally a good limit

2020-07-13 15:08 UTC, aathn commented on src/visual/boot.js
> +	});
This should be made into a function to avoid code duplication

2020-07-13 15:08 UTC, aathn commented on src/model/dfa.mc
> +--utest nextState 1 newDfa.graph '0' with 2 in
If these aren't needed, they should be removed, and if they don't pass, they should be fixed

2020-07-13 15:08 UTC, andersthune commented on src/model/state.mc
> +     eqs: fun_eq,
Typo here: `state2tring`
I'm guessing the type signatures should be `a -> String` and `a -> a -> Bool`

2020-08-04 09:18 UTC, david-broman reviewed
Some general comments:
- You need to document the protocol between the server and the client. Is this done in the other PR?
- When I tested the file `test/test.mc` the second DFA works, but the first gives an unexpected behaviour. It says that the first DFA is stuck, even if the first input should be accepted. It seems like the error check is one token ahead. I think you need to create many more test cases to really test the DFAs. Please add these tests to the repo.

2020-08-04 09:18 UTC, david-broman commented on README.md
> +
If this is the first time you use the library, you would like to start quickly by running an example. It would be better if you have an getting started example, explain where it is and how to run it.

2020-08-04 09:18 UTC, david-broman commented on README.md
> +	let alfabeth = [L_1, L_2,..]
I think it is mentioned before, but the 'alphabet' is misspelled.

2020-08-04 09:18 UTC, david-broman commented on README.md
>  This will prompt you to the port on your localhost on which the server is started, now if you modify and save the dfa, it should generate a file called **data-source.js** and reflect the update in th
Later in the text, the text about `test.mc` does not seems to be up to date. It is not in the root anymore. 

The following sentence is unclear
"If you want to write your own, make sure to source the gen.mc properly:"

What do you mean by source gen.mc?

2020-08-04 12:09 UTC, closed without merging